/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.*;
import javax.swing.JOptionPane;
import project.ConnectionProvider;
/**
 *
 * @author pushp
 */
public class AddBook extends javax.swing.JFrame {

    /**
     * Creates new form AddBook
     */
    public AddBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        b_publisher = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b_id = new javax.swing.JTextField();
        b_price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        b_year = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        b_qty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Publisher");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 126, -1));

        b_name.setBackground(new java.awt.Color(204, 255, 204));
        b_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nameActionPerformed(evt);
            }
        });
        getContentPane().add(b_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 250, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Book Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 126, -1));

        b_publisher.setBackground(new java.awt.Color(204, 255, 204));
        b_publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_publisherActionPerformed(evt);
            }
        });
        getContentPane().add(b_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 250, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Book Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 126, -1));

        b_id.setBackground(new java.awt.Color(204, 255, 204));
        b_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_idActionPerformed(evt);
            }
        });
        getContentPane().add(b_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 250, 30));

        b_price.setBackground(new java.awt.Color(204, 255, 204));
        b_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_priceActionPerformed(evt);
            }
        });
        getContentPane().add(b_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 250, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 126, -1));

        b_year.setBackground(new java.awt.Color(204, 255, 204));
        b_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_yearActionPerformed(evt);
            }
        });
        getContentPane().add(b_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 250, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Publishing Year");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 126, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 126, -1));

        b_qty.setBackground(new java.awt.Color(204, 255, 204));
        b_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_qtyActionPerformed(evt);
            }
        });
        getContentPane().add(b_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 250, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/save-icon--1.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 150, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/red-x-mark-transparent-background-3.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 150, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/123456.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_nameActionPerformed

    private void b_publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_publisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_publisherActionPerformed

    private void b_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_idActionPerformed

    private void b_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_priceActionPerformed

    private void b_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_yearActionPerformed

    private void b_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_qtyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String bookId = b_id.getText();
       String bookName = b_name.getText();
       String bookPubliser = b_publisher.getText();
       String bookPrice= b_price.getText();
       String bookYear = b_year.getText();
       String bookQty = b_qty.getText();
       if(bookId.equals("")||bookName.equals("")||bookPubliser.equals("")||bookPrice.equals("")||bookYear.equals("")||bookQty.equals("")){
        JOptionPane.showMessageDialog(null, "Invlid Entry!");
       }
       else{
           
     
        try {
            // TODO add your handling code here:
           
            Connection con= ConnectionProvider.getCon();
            Statement st;
            st= con.createStatement();
            st.executeUpdate("insert into books values('"+bookId+"','"+bookName+"','"+bookPubliser+"','"+bookPrice+"','"+bookYear+"','"+bookQty+"')");
            JOptionPane.showMessageDialog(null, "Successfully Added");
            this.dispose();
            new AddBook().show();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
       }
          

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b_id;
    private javax.swing.JTextField b_name;
    private javax.swing.JTextField b_price;
    private javax.swing.JTextField b_publisher;
    private javax.swing.JTextField b_qty;
    private javax.swing.JTextField b_year;
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
